name: Milepost

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  SwiftPM:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Run Tests
      run: |
        swift test --verbose
