name: Milepost

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  Tests:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_14.0.app/Contents/Developer'
    - name: Run Tests
      run: |
        swift test --verbose
